from tkinter import *
root = Tk(className="examplegui")
label = Label(root, text="Click the Button Below to Display Hello World in Terminal")
button1 = Button(root, text="Click Here for Hello World in Terminal", command=lambda: print("Hello World!"))
button2 = Button(root, text="Click Here for Absolutely Nothing")
label.pack()
button1.pack()
button2.pack()
root.title("examplegui")
root.mainloop()